[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eca101489ec80bc3e41c97af128bdfb303ebded7"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "c11dc66b2230d1446cff1fbfa345d71ba486c1d76ec6dea62e0478c6d902832c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2103b614ca02fffa0f8b1850fdbc7ed8803802bb"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "c11c2ad619b11842330809540bfa547fa7f7be870d148554210affb0dfcd921a"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.6.3.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d813e6414b0d373051bdf6d4dc39394c9930b6b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "189561cdba1cb748ad92a10e3e3160d07521fa3b495856b69f774f6ec1596bab"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c66bc7968aa35e7f3c08f3b218158c9cd1ea09c9"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "05973e31bf5d847deea0c23fd387cd2f48692e0e0bee729ef65c068c2e2360e1"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eca101489ec80bc3e41c97af128bdfb303ebded7"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "c11dc66b2230d1446cff1fbfa345d71ba486c1d76ec6dea62e0478c6d902832c"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f02853615628780ec90e912598ad571a592e91c3"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "a1373643adee33a64055b4b1e4879d33c24fa432b3b1bd49c2a79440a54064cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48601ba90fca5989c5902a321d70e5f601b8bab6"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "9dede6b9897f72f9d2641aaaad04a623565abcb75c934da065c48bcfb3109c15"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.6.3.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44bbdb51f91ab1a9f07d63d42c7252cb609082d7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "b4982972f0e07b77bd8d0fe1f416e47946fb9a2276784fb66f2a35f2e8ef854b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cbeb059b1359f00fbf7de0c63a516e3c7f2da31"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "087ea73948c16c2534c192bc083a2cb75104c4bc55e9c66e59f85b06dd12736d"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f02853615628780ec90e912598ad571a592e91c3"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "a1373643adee33a64055b4b1e4879d33c24fa432b3b1bd49c2a79440a54064cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+3/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
