[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1eba69a4042d9fe5d5f4bf9722e6993027ab4f0a"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "4802e709ea035e95fed5a3c5255eccd921398deb5cf8bb8d263babe8baf3da0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+0/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2843cee008feb52920e66d1fe7e82efffa85408a"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "a3eddf4dfa07fd17dac6b20f26e09f307af56bcc1e0eea11c139cb6c5ea0972b"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+0/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11.tar.gz"
