[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e67b6be2c3c876ac4a94c695299c08d83777397"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "1858a19b527d00ed5e6931ba0da5c54a71e0879cfd41cd2d200ce4a6637d5c52"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.6.3.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "368d13199ec8aa688f6ee885a2beb9e328dd979d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "5ff02194a26bc7d072d3c5e1a175b310ea52616fae6dd95f42afe7597d17d2d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "929a3ac70435f8be4dfe350be7a87477d6c74c29"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "f87c49692eae47c66644a67a57f12f5d49daef35c4d5544cc5d14c3ad81581b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61b39d09b7494d34b3b609930a527c3310a17ddd"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "f97c197b511e82ce8ecca50651fc41f16c58bdc3399bb0bceb9780c4a73b49a3"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.6.3.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75397c34455fa6590b662e63ffc4e0c8507f15e8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "0a4b313c42dafd2a58a6d05b14938f9d2d5cba18f95722d86ad01c3952218aa7"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb5448fb11f110e36399c529c7864ae1c8ecf588"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "7ac244aa7c0bee9235c9df31b19b900d98deaea14faa8cde3249552a7a717992"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v1.1.1+2/OpenSpiel.v1.1.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
