[[OpenSpiel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4feff2b890c7d8c6a145c32e36f079203132a3a9"
libc = "glibc"
os = "linux"

    [[OpenSpiel.download]]
    sha256 = "57d3c692b44724cbe6452c0b7683ddf58e4350f2623e2ded3d5775c22686bc38"
    url = "https://github.com/JuliaBinaryWrappers/OpenSpiel_jll.jl/releases/download/OpenSpiel-v0.1.1+0/OpenSpiel.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
